Fixed Compile Errors
PDFTron/webviewer-vue-sample pull request #55
Opened 2024-09-18 11:30 UTC by hussam-apryse

- With `vue-cli` now in maintenance mode, the scaffolding of the project has been updated to use `vite`, as [recommended](https://vuejs.org/guide/scaling-up/tooling.html#vue-cli) by the developers of Vue. This includes changes mentioned by the [migration guide](https://vueschool.io/articles/vuejs-tutorials/how-to-migrate-from-vue-cli-to-vite/) 
- `vue-cli` dependencies and scripts removed and replaced with `vite` dependencies and scripts
- Babel and `babel.config.js` removed in order to provide support for only modern browsers
- `index.html` moved to the repo's root.
- `vite` SVG files used for icons instead of PNG images
- `process` environment variable replaced with the `import.meta` environment variable used by `vite` in `src/components/WebViewer.vue`
- `copy-webviewer-files.js` changed to use `import` as an ES module instead of `require` as CommonJS
- With the `eslintConfig` key in `package.json` [no longer supported](https://github.com/eslint/eslint/discussions/18131) in the latest versions of ESLint. Linting in the project was changed to to use a flat `eslint.config.mjs` config file with the rules mentioned in the `CONTRIBUTING.md` guide

2024-10-10 19:02 UTC, mparizeau-pdftron requested changes

2024-10-10 19:02 UTC, mparizeau-pdftron commented on LICENSE
> +Copyright 2024 PDFTron Systems Inc. All rights reserved.
Can we change this to Apryse Software

2024-10-13 10:09 UTC, hussam-apryse commented on LICENSE
> +Copyright 2024 PDFTron Systems Inc. All rights reserved.
Done

2024-11-19 18:37 UTC, mparizeau-pdftron approved these changes

2024-11-19 18:37 UTC, merged